[font]
normal = { family = "Iosevka", style = "Regular" }
size = 12

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "e", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|go‐ pher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
action = "Copy"
binding =  { key = "w", mods = "Control|Shift" }
regex = "[-'\"$~./:_a-zA-Z.0-9?+@äöüß]+"

[[hints.enabled]]
action = "Copy"
binding =  { key = "l", mods = "Control|Shift" }
regex = "^.*$"

[[hints.enabled]]
action = "Copy"
binding =  { key = "t", mods = "Control|Shift" }
regex = " -> [_0-9a-zA-Z,|\\[\\] ]+"

[env]
# This makes 256-color support in tmux work
TERM = "xterm-256color"
