theme = "mytheme"

[editor]
text-width = 88
rulers = [88]
cursorline = true
cursorcolumn = true
bufferline = "multiple"
color-modes = true
idle-timeout = 0
true-color = true

[editor.whitespace.render]
# space = "all"
nbsp = "all"
tab = "all"
space = "trailing"

[editor.statusline]
center = ["version-control"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[keys.insert]
"C-[" = "normal_mode"

[keys.select]
"C-[" = "normal_mode"
