theme = "mytheme"

[editor]
text-width = 88
rulers = [88]
cursorline = true
cursorcolumn = true
bufferline = "multiple"
color-modes = true
true-color = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"

[editor.whitespace.render]
# space = "all"
nbsp = "all"
tab = "all"
# space = "trailing"

[editor.statusline]
center = ["version-control"]

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-progress-messages = true

[keys.insert]
"C-[" = "normal_mode"

[keys.select]
"C-[" = "normal_mode"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
W = ":reflow"
