[language-server.efm]
command = "efm-langserver"
# config.documentFormatting = true

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

[[language]]
name = "python"
language-servers = [
  # "efm",
  "ruff",
  "pyright",
]
