[language-server.efm]
command = "efm-langserver"
# config.documentFormatting = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.black-lsp]
command = "black-lsp"
args = ["--stdio"]
config = {}

[[language]]
name = "python"
language-servers = [
  # "efm",
  "ruff",
  "pyright",
  "black-lsp"
]
