[language-server.efm]
command = "efm-langserver"
# config.documentFormatting = true

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

[language-server.typos]
# typos-lsp must be on your PATH, or otherwise change this to an absolute path to typos-lsp
command = "typos-lsp"
# Logging level of the language server. Defaults to error.
# Run with helix -v to output LSP logs to the editor log (:log-open)
environment = {"RUST_LOG" = "error"}
# Custom config. Used together with a config file found in the workspace or its parents,
# taking precedence for settings declared in both. Equivalent to the typos `--config` cli argument.
# config.config = "~/code/typos-lsp/crates/typos-lsp/tests/typos.toml"
# How typos are rendered in the editor, can be one of an Error, Warning, Info or Hint.
# Defaults to Warning.
# config.diagnosticSeverity = "Warning"

[[language]]
name = "python"
language-servers = [
  "ruff",
  "basedpyright",
  "typos"
]

[[language]]
name = "javascript"
language-servers = [
  { name = "efm", only-features = [ "diagnostics" ] },
  { name = "typescript-language-server", except-features = [ "format" ] },
]
[[language]]
name = "html"
auto-format = false

[[language]]
name = "css"
auto-format = false

# Add ispc
# See https://github.com/helix-editor/helix/pull/8678 for proper support
[[language]]
name = "cpp"
file-types = ["cc", "hh", "c++", "cpp", "hpp", "h", "ipp", "tpp", "cxx", "hxx", "ixx", "txx", "ino", "C", "H", "cu", "cuh", "cppm", "h++", "ii", "inl", "ispc"]
